import requests
import pandas as pd
from datetime import datetime

print("Initiating Historical Time-Series API Pipeline...")

# 1. THE TIME-SERIES ENDPOINT
# This targeted endpoint pulls historical granularity rather than a single price snapshot
endpoint = "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart"

params = {
    'vs_currency': 'usd',
    'days': '30',
    'interval': 'daily'
}

# 2. THE REQUEST WITH ERROR HANDLING
response = requests.get(endpoint, params=params)

if response.status_code != 200:
    print(f"CRITICAL ERROR: API Connection Denied. Status Code: {response.status_code}")
    exit()

print("Historical payload received successfully. Initializing data translation...")

# 3. PARSING THE NESTED JSON
raw_json = response.json()
raw_prices = raw_json['prices']  # Array of [timestamp, price] pairs

# 4. TRANSFORMATION AND TIMESTAMP CONVERSION
time_series_vault = []

for data_point in raw_prices:
    unix_timestamp = data_point[0]
    price_usd = data_point[1]
    
    # Convert Unix epoch milliseconds into a human-readable clean date format
    clean_date = datetime.fromtimestamp(unix_timestamp / 1000).strftime('%Y-%m-%d')
    
    time_series_vault.append({
        'Date': clean_date,
        'Asset': 'BTC',
        'Closing_Price_USD': round(price_usd, 2)
    })

# 5. LOAD INTO MATHEMATICAL MATRIX
df = pd.DataFrame(time_series_vault)

# Drop any duplicate date entries generated by the API's server-side logging
df = df.drop_duplicates(subset=['Date'])

print("\n--- TIME-SERIES SECURED: LAST 30 DAYS HISTORICAL INDEX ---")
print(df.tail(10))  # Preview the most recent 10 days

# 6. EXPORT TO CSV
output_filename = 'historical_bitcoin_30d.csv'
df.to_csv(output_filename, index=False)

print(f"\nPipeline Closed. Historical dataset secured to '{output_filename}'")